"""Junior quickstart.

Runs end-to-end against the shipped synthetic ``Test_Patient`` fixture using
local model folders under ``models/``. No API keys or remote LLM endpoint are
needed, but the local model weights must already be present.

Run it with ``python quickstart.py``. It also opens cleanly in VS Code or
JupyterLab because every ``# %%`` cell stops at a natural rest point.

For your own cohort, do NOT edit this file. Instead:

    cd /path/to/my_study
    junior new-project

...which writes a ``junior_<project>.yaml`` describing that cohort and creates
its folders. Every ``junior`` command run from there then uses it. The runner this
file calls lives in ``src/jr_pipeline/runtime_infrastructure/cohort_runner.py``
and is shared with the app, so a fix here lands for every cohort.
"""
import os
from pathlib import Path

from jr_pipeline.runtime_infrastructure.cohort_runner import (
    CohortSettings,
    check_phi_containment,
    print_slurm_commands,  # noqa: F401  (used by the commented SLURM block below)
    run_cohort,
    view_results,
)

# This demo runs on the SYNTHETIC Test_Patient fixture (no real PHI), so show the
# extracted values on stdout. Real cohorts leave this unset and values are redacted
# by default (see _stdout_values_allowed in cohort_runner).
os.environ.setdefault("JR_SHOW_STDOUT_VALUES", "1")


# %%
DEMO_SETTINGS = CohortSettings(
    # Cohort identity.
    project="Quickstart_Demo",
    input_folder=Path("./examples"),
    data_root=Path("./data"),

    # Patient folders under input_folder.
    patients=["Test_Patient"],

    # Source files to preserve as structured parquet.
    # "auto" means every supported file in examples/Test_Patient, all columns.
    files_to_ingest="auto",

    # Text to embed, then index in HNSW.
    # "auto" means the `text` column from every ingested parquet that has one.
    files_to_embed="auto",

    # Variables to extract. Names must match recipe folders.
    variables=["date_of_birth"],
    recipes_root=Path("./var_extraction_recipes"),

    # Local embedding model folder. Embed intentionally does not download models.
    embedding_model_path=Path(
        "./models/embedding/thomas-sounack:BioClinical-ModernBERT-base23APR2026"
    ),

    # Local extraction model folder. In local mode the runner writes a temporary
    # run-local allowlist pointing at this exact path, so no network endpoint is used.
    llm_mode="local",
    llm_local_model_path=Path("./models/extraction/3B_param_local_qwen_extractor_for_example"),
    # Used when llm_mode is not "local"; kept here so switching to an
    # institutional allowlist is an explicit settings change.
    llm_allowlist=Path("./deployment/local/llm_allowlist.yaml"),
    llm_endpoint_name=None,
)


# %%
def _missing_model_folders() -> list[Path]:
    """Neither model is downloaded for you, and without them the run reaches embed and
    fails per patient on a message about a malformed Hub id — which names neither the
    setting nor the folder. Say it once, up front, in the words of this file."""
    return [
        p for p in (DEMO_SETTINGS.embedding_model_path, DEMO_SETTINGS.llm_local_model_path)
        if p is not None and not Path(p).is_dir()
    ]


# %%
if __name__ == "__main__":
    absent = _missing_model_folders()
    if absent:
        raise SystemExit(
            "These model folders are not there:\n"
            + "".join(f"  {Path(p).resolve()}\n" for p in absent)
            + "Junior loads models from disk and never downloads them. Fetch each one, "
            "e.g.\n  hf download <hub-id> --local-dir <that folder>\n"
            "models/models_registry.yaml names the model behind each folder."
        )

    result = run_cohort(DEMO_SETTINGS)
    view_results(result, DEMO_SETTINGS)
    check_phi_containment(DEMO_SETTINGS)
    # Uncomment to see the SLURM submission commands for 500-patient scale:
    # print_slurm_commands(DEMO_SETTINGS, run_id=result.run_id)
